namespace Arrowgene.DJMaxOnline.Server;

public enum PacketId : ushort
{
    // OnInitialize = 0x00, - Not a Packet
    // OnRegister = 0x00, - Not a Packet
    // Resume = 0x00, - Not a Packet
    // OnConnect = 0x00, - Not a Packet
    // ClearChannelInfo = 0x00, not a packet
    // InitReq = 0x00, not a packet
    // Suspend = 0x00, not a packet
    // OnDestroy = 0x00, not a packet
    // OnDisconnect = 0x00, not a packet
    // ClearWaiterInfo = 0x00,  not a packet
    // ClearJoinerInfo = 0x00,not a packet
    // ClearCourseList = 0x00, not a packet
    // ClearUserIdInfo = 0x00,not a packet
    // ClearRoomInfo = 0x00, not a packet
    //EraseRoomInfo = 0x00, not a packet
    //EraseJoinerInfo = 0x00, not a packet
    //EraseWaiterInfo = 0x00, not a packet
    //UpdateWaiterInfo = 0x00, not a packet
    //AuthenticateInReq = 0x00,  // maybe only for korea and japanese client?
    //UpdateRoomInfo = 0x00, not a packet
    //Report = 0x00, // what is this? sub_438FD0

    Test00 = 0x6f, // delete for testing 
    ProbeObfuscated = 0xF0, // delete for testing 
    sub_434390 = 0x83, //0xD 
    sub_434450 = 0x85, //0xD
    sub_434510 = 0x87, //0xD
    sub_434620 = 0x8A, //0xB
    sub_434B40 = 0xFD, //0xD
    sub_435F20 = 0x53, //0xC
    sub_436120 = 0xA3, //0xB
    sub_4362D0 = 0x56, //0xC
    sub_437370 = 0x72, //0x103
    sub_437900 = 0x23, //0xF
    sub_432210 = 0x12C, //0xB
    sub_4323D0 = 0x12F, //0x26
    OnUpdateJoinerInfoInf = 0x51, //FIXED 135
    ConnectReq = 0x0A, // SERVER:47, client:23 (CLIENT VERSION)
    OnConnectAck = 0x09, //0x2F
    AuthenticateInSndAccReq = 0x11, 
    AuthenticateInSndeKeyAck = 0x13, 
    OnAuthenticateInAck = 0x10,  
    OnAuthenticateInSndeKeyReq = 0x12, //0x8
    OnAuthenticateInSndrPwdReq = 0x14, //0x9
    AuthenticateInSndrPwdAck = 0x15,  //0x14
    OnUbsAccountAuthenResAck = 0x12D, // ?? 
    OnUbsAwardInfoInf = 0x12E, //176
    OnUbsAwardAuthenAck = 0x130, // ??
    KeepAuthenticateInReq = 0x17, 
    OnKeepAuthenticateInAck = 0x16, 
    LogInReq = 0x1B, 
    OnUserInfoInf = 0x43, 
    OnInventoryInfoInf = 0x44, 
    OnMessengerInfoInf = 0x45, 
    OnLogInAck = 0x1A,
    LogOutReq = 0x19, //0xDu
    OnLogOutAck = 0x18,
    OnChannelInfoInf = 0x0B, 
    OnPeerCountInf = 0x0C, 
    OnDisconnectPeerInf = 0x08, //??
    AliveAck = 0x06, 
    OnAliveReq = 0x07, 
    OnPingTestInf = 0x03, 
    PingTestInf = 0x04, 
    UserInfoReq = 0x1D, 
    OnUserInfoAck = 0x1F, //??
    OnUserInfoResNotFound = 0x1E, //??
    OnBigNewsInf = 0x97,//??
    OnChatInf = 0x39, // game sends 0x38.
    OnWChatInf = 0x37, //maybe same pattern?(0x36)
    OnCourseListInf = 0x82, //??
    OnCourseRankAck = 0x84, //??
    OnChangeCourseAck = 0x86, //??
    OnContinueCourseAck = 0x88, //??
    OnPostCourseItemReq = 0x89, //??
    OnAwardItemInf = 0x8C, //??
    OnCipherCommandInf = 0x10E, //admin command based on csv? is this even used? 
    OnEnvironmentInf = 0xFC, 
    OnSystemInfoAck = 0xFE, //??
    OnWaiterInfoUpdateInf = 0x3C, 
    OnWaiterInfoEraseInf = 0x3D, //??
    OnRoomInfoUpdateInf = 0x3A, 
    OnRoomInfoEraseInf = 0x3B, 
    UserIdInfoReq = 0x21, // ??
    OnUserIdInfoAck = 0x22, 
    OnUserIdInfoInf = 0x20, 
    OnJoinerListStart = 0x40, //??   
    OnJoinerListEnt = 0x41, //??  
    OnJoinerListEnd = 0x42, //??
    CreateRoomReq = 0x4C, 
    OnCreateRoomAck = 0x4D, 
    JoinRoomReq = 0x46, 
    OnJoinRoomAck = 0x47, 
    OnPostJoinRoomInf = 0x48,
    InviteRejectReq = 0xA6, 
    OnInviteRejectAck = 0xA7,
    OnRoomDescInf = 0x50, // Fixed 48
    OnQuickInviteAck = 0xA1, // not captured
    OnInviteReq = 0xA2, // not captured
    QuickInviteReq = 0xA0, // not captured
    RoomChangeInfoReq = 0x9C, //FIXED 50
    OnRoomChangeInfoAck = 0x9D, //FIXED 51
    TeamControlReq = 0x58, // FIXED 12
    OnTeamControlInf = 0x59, //FIXED 13
    OnGameTypeInf = 0x5B,//FIXED 12
    ReadyReq = 0x5D,  // FIXED 11
    OnReadyInf = 0x5E, // FIXED 18
    StartReq = 0x5F, // not captured
    OnStartInf = 0x60, // Fixed 14
    OnJoinEventInf = 0x61, // GO BACK TO THIS.
    OnEventInfoInf = 0x63, // not captured
    PlayStartReq = 0x64, // Fixed 11
    OnPlayStartInf = 0x65, // Fixed 11
    PlaySkipReq = 0x67, // FIXED 11
    OnPlaySkipInf = 0x68,//FIXED 11
    PlayOverReq = 0x6A, // not captured
    OnPlayOverInf = 0x6B, // not captured
    PlayStateInf = 0x6C, // FIXED 30
    OnPlayStateInf = 0x6D,// FIXED 23
    OnCheckDataReq = 0x71, //FIXED 15
    OnLoadCompleteInf = 0x7C, //FIXED 12
    StageResultInf = 0x49, // not captured, Maybe wrong ID.
    OnStageResultExInf = 0x70, //FIXED 51
    LeaveRoomReq = 0x73, // FIXED 11
    OnLeaveRoomAck = 0x74, // FIXED 14
    ChangeDiscReq = 0x76, // FIXED 17
    OnChangeDiscInf = 0x77,//FIXED 17
    OnAwardInfoInf = 0x78, // not captured
    OnGameInfoInf = 0x7A, //Very Large Fixed.
    UpdateUserAccountNickReq = 0x30,  // not captured
    OnUpdateUserAccountNickAck = 0x31, // not captured
    UpdateUserProfileReq = 0x32,  // not captured
    OnUpdateUserProfileAck = 0x33, // not captured
    OnUpdateUserIconInf = 0x24, // not captured
    OnUpdateUserPropertyInf = 0x25, //Fixed 73
    OnUpdateUserPropertyRecordInf = 0x28, // not captured
    OnUpdateUserPropertyMiscInf = 0x29,//FIXED?? 49
    OnUpdateUserPropertyLevelInf = 0x26, //FIXED 15
    OnUpdateUserPropertyMoneyInf = 0x27, //FIXED 15
    OnUpdateUserInventoryDefaultItemInf = 0x2A,  // FIXED 199
    OnUpdateUserInventoryEventItemInf = 0x2B, // not captured
    OnUpdateUserInventoryShopItemInf = 0x2C, // not captured
    OnUpdateUserInventoryMountItemInf = 0x2D, // not captured
    OnUpdateUserInventoryPresentItemInf = 0x2E, // not captured
    GetItemReq = 0xB4, //FIXED 11
    OnCrItemInf = 0xB3, //FIXED 11
    OnGetItemFail = 0xB5, // not captured
    OnGetItemAck = 0xB6, //FIXED 15
    ItemLevelUpReq = 0xB7,  // FIXED 11
    OnItemLevelUpFail = 0xB8, // not captured
    OnItemLevelUpAck = 0xB9, //FIXED 14
    UseItemReq = 0xBA, // not captured
    OnUseItemFail = 0xBB,// not captured
    OnUseItemAck = 0xBC, // not captured
    OnGoodLuckInf = 0xBD, // not captured
    OnGoodLuckListInf = 0xBE, // not captured
    OnMissionStandItemInf = 0xC0, //fixed 22
    UseEffectorInf = 0xC3,  //fixed 35
    UseEffectorSetInf = 0xC5, //fixed 19
    OnUseEffectorInf = 0xC4, //fixed 36
    OnUseEffectorSetInf = 0xC6, // not captured
    UseMountItemInf = 0xC8, // not captured
    OnUseMountItemInf = 0xC9, // not captured
    OnStartParameterInf = 0xCA, // not captured
    OnBillingAuthInf = 0xD2, // not captured
    OnGameStartInf = 0xD3, // not captured
    OnUserAlertInf = 0xD4, // not captured
    MountItemReq = 0xD7, // not captured
    OnMountItemAck = 0xD8, // not captured
    GetPresentItemReq = 0xD9, // not captured
    OnGetPresentItemAck = 0xDA, // not captured
    DeleteItemReq = 0xDB, // not captured
    OnDeleteItemAck = 0xDC,// not captured
    OnExpiredMountItemInf = 0xE4, // not captured
    OnExpiredShopItemInf = 0xE5, // not captured
    OnAlertCreditInf = 0xE6, //Dynamic
    OnMsgNotifyInf = 0xF1, //Fixed 17
    MsgRegisterUserReq = 0xF2, // not captured
    OnMsgRegisterUserAck = 0xF3, // not captured
    OnMsgRegUserInf = 0xF4, // not captured
    OnMsgBlkUserInf = 0xF5, // not captured
    OnMsgGroupInf = 0xF6, // not captured
    PurchaseItemReq = 0xDD,  // not captured
    OnPurchaseItemAck = 0xDE, // not captured
    ResaleItemReq = 0xDF, // not captured
    OnResaleItemAck = 0xE0, // not captured.
    OnUpdateUserAccountClassInf = 0x2F,  // seems fixed 239, not sure what this does though
    VerifyCodeInf = 0xE7, //fixed 35
}
